### ISSUE TITLE
Broker and DAPS interaction

### ISSUE THREAD

**Issue by AnaCarolinaChaves** [International-Data-Spaces-Association/metadata-broker-open-core#117]
I have two virtual machines:

- Machine 1- it has a DAPS server and a Metadata Broker server, both being initialized with docker compose (one for each)
- Machine 2 - has two Dataspace connectors.

I was able to make the machine 2 connectors interact with the DAPS without error. However, when I changed the broker to use the local DAPS, the connectors logs is:
`PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`

To change the Broker DAPS server I executed the following on the Broker directory:
1. Remove volumes (`docker-compose down -v`)
2. Change the `daps.crt `file from `docker/broker-core/` to the one created with the local DAPS
3. Update the files from directory `cert `from the docker-compose 

- server.crt and server.key from the certificated created in local DAPS for the broker (server.crt is the same as  `daps.crt ` )
- isstbroker-keystore.jks - by creating a .p12 file with the previous files and then converted it to .jks

4. Run the following commands:
```
mvn clean package
cp broker-core/target/broker-core-5.0.0-SNAPSHOT.jar docker/broker-core
cd docker/broker-core
docker build -t registry.gitlab.cc-asp.fraunhofer.de/eis-ids/broker-open/core .
cd ../../docker/composefiles/broker-localhost/
docker-compose up
```

**Comment by AnaCarolinaChaves** [comment]
I was able to fix this issue on the connector said.
However, now when I try to communicate with the Dataspace connector (which is using the local DAPS correctly) the response is shown in the following picture. There are no more details in the logs (connector or broker). So I'm not sure which component, or why, is returning the error.
<img width="524" alt="respostaConnectorAoBrokerComDAPS" src="https://user-images.githubusercontent.com/37149360/174090703-a9591a62-6057-43e6-82d9-494c52397137.PNG">

**Comment by SebastianOpriel** [comment]
Have you tried to set log level in

**Comment by AnaCarolinaChaves** [comment]
The DSC is set to debug. The broker was not.
However, I was able to fix the problem while resolving the error another component was generating. The problem was that the URL the broker was trying to connect was the old URL. Updating the DAPS proxy fixed this.

**Comment by SebastianOpriel** [comment]
It would be great, if you could give the broker developers a hint, which line was wrong and what the correct value is. Thus, I expect the issue as "not resolved" yet.

**Comment by AnaCarolinaChaves** [comment]
The developers added the line to redirect to the correct URL a couple of days ago. I was just using the older one.
