### ISSUE TITLE
Reouse Update Message Wrong ID

### ISSUE THREAD

**Issue by hantongliu** [International-Data-Spaces-Association/metadata-broker-open-core#19]
When we do a resource update message, the hash id of the resource will be changed.
From the reource catalog:
 "offeredResource": [
        "http://localhost:8080/connectors/541260824/1487174079/-715517746",
        "http://localhost:8080/connectors/541260824/1487174079/1538291463"
    ],
From Fuseki:
?s ids:version ?o.
  | s | o
-- | -- | --
1 | <http://localhost:8080/connectors/541260824/1487174079/-715517746> | "1.1"
2 | <http://localhost:8080/connectors/541260824/1487174079/1538291463> | "v0.0.1"
3 | <http://localhost:8080/connectors/541260824/1487174079/-871940353> | "1.2"

The version 1.2 should replace 1.1 with the hash id -715517746.
Both of -715517746 and -871940353 have the same "owl#sameAs" id.

**Comment by hantongliu** [comment]
The REST has has the same issue. Tried to updated the same resource. Got:

  | s | o
-- | -- | --
1 | <http://localhost:8080/connectors/541260824/1487174079/-715517746> | "1.1"
2 | <http://localhost:8080/connectors/541260824/1487174079/1538291463> | "v0.0.1"
3 | <http://localhost:8080/connectors/541260824/1487174079/-871940353> | "1.2"
4 | <http://localhost:8080/connectors/541260824/1487174079/251690986> | "1.2"

**Comment by maboeckmann** [comment]
Very interesting indeed. The last number of the slash should depend on the URI provided in the "sameAs" only. I will look into this

**Comment by maboeckmann** [comment]
Thanks for the issue report. I found out that resource URIs were rewritten incorrectly (rewritten twice) in case of them being updated via ResourceUpdateMessages. This is fixed in #20 - could you kindly make sure that the issue is resolved now, please?

**Comment by hantongliu** [comment]
After the fix, now the resource update works as expected.
