### ISSUE TITLE
Problem on visualising the resource metadata on broker.mobilitydataspace.io 

### ISSUE THREAD

**Issue by edgardmarx** [International-Data-Spaces-Association/metadata-broker-open-core#29]
Dear all,

There is a problem when browsing registered resources in broker.mobilitydataspace.io.

When visualising resource details, the message "unknown resource" is being displayed:

https://broker.mobilitydataspace.io/resources/resource?id=https%3A%2F%2Fbroker.test.mobilitydataspace.io%2Fconnectors%2F-636973515%2F1526728165%2F-874736873

![Screenshot 2021-05-20 at 15 07 40](https://user-images.githubusercontent.com/4638593/118983914-3ec3c500-b97d-11eb-92f5-4efebeddf121.png)

However, the problem seems to not occur at the test broker (broker.test.mobilitydataspace.io).

https://broker.test.mobilitydataspace.io/connector/connector?id=https%3A%2F%2Fbroker.test.mobilitydataspace.io%2Fconnectors%2F-636973515

![Screenshot 2021-05-20 at 15 08 03](https://user-images.githubusercontent.com/4638593/118984006-57cc7600-b97d-11eb-9078-ebff8c5ec190.png)

**Comment by sebbader** [comment]
Hello @edgardmarx, the two instances run slightly different versions (test is more up to date, also with potentially unsafe updates). I assume that this bug is a bit older and already solved with the currently deployed update to the test instance but hasn't made it to the non-test instance yet.
Can you continue your work with the test instance for now?

**Comment by sebbader** [comment]
@sebplorenz do we have a time plan already when we can put the latest update to the main instance?

**Comment by edgardmarx** [comment]
@sebbader yes, I can use the test for now, but It will be useful to have the information on when the MDS broker will be updated as well as which versions (model inbound / outbound) or Connector version will be supported. These are critical information to any third-party application currently integrated.
It seems that my connector version (v4.3.1) is supported in the test version.
@sebplorenz, I suggest the creation of a mailing list (e.g. groups.google.com) "MDS broker list" to share information such as new releases or schedule maintenances as well as to discuss related problems with important stakeholders.

**Comment by NehaThawani44** [comment]
This issue is similar to the issue  mentioned and we are working on resource indexing fixes and UI fix.https://github.com/International-Data-Spaces-Association/metadata-broker-open-core/issues/36

**Comment by NehaThawani44** [comment]
This issue no longer exist in the latest version of the broker 4.2.4- SNAPSHOT hence closing this issue now.
