### ISSUE TITLE
Connection to a local DAPS

### ISSUE THREAD

**Issue by aitorce** [International-Data-Spaces-Association/metadata-broker-open-core#33]
Some background information:
I am currently working on setting up the Testbed. We are in the process of connecting the Dataspace Connector, a local AISEC DAPS and the Metadata Broker open core. We are still working out how to make the connector use our local DAPS as we have found some issues with the IDS Infrastruture. 

The open issue can be found here:
https://github.com/International-Data-Spaces-Association/DataspaceConnector/issues/323

I assume we will have a similar issue with the Broker. I have not been able to find the file where you specify the DAPS you want to connect to. We need to replace the DAPS url. 

https://daps.aisec.fraunhofer.de -> http://localhost:4567/token (the DSC was trying to point at http://localhost:4567/v2/token which is not the case here).

Where can I find the file to replace the DAPS url?

Thank you in advance

**Comment by tmberthold** [comment]
The url seems to be in the application.properties of the broker-core and can be changed:
https://github.com/International-Data-Spaces-Association/metadata-broker-open-core/blob/357f5a71a26b9b9f44e45a4511d1cd86b62a49cc/broker-core/src/main/resources/application.properties#L19

**Comment by NehaThawani44** [comment]
@maboeckmann Closing this as the daps.url is configured as stated.
