### ISSUE TITLE
Broker UI

### ISSUE THREAD

**Issue by mikhail-gordienko** [International-Data-Spaces-Association/metadata-broker-open-core#34]
Hello!

Is there any UI for the broker? I expected to find it in the broker-core project, but it appeared to be REST-only.
What about the UI used in this [video](https://www.youtube.com/watch?v=zk0N6u5ewOA)? 
Is it public?

**Comment by maboeckmann** [comment]
Dear @mikhail-gordienko ,
the UI which is shown in that video is not open-source. The open-source includes all message handlers and IDS endpoints but does not provide an indexing module for fast web access, nor a UI. The enterprise edition comes with indexing built on Elasticsearch to provide quick access for a responsive frontend.
If you'd like to click through the interface a bit, then we have a public demo instance hosted at https://demo3.iais.fraunhofer.de/connector

**Comment by NehaThawani44** [comment]
Hello @mikhail-gordienko ,
Closing this issue as @maboeckmann has provided the UI for our demo instance https://demo3.iais.fraunhofer.de/connector.
Please let us know if you need any further information.
