### ISSUE TITLE
Connectors disappear at midnight

### ISSUE THREAD

**Issue by sebplorenz** [International-Data-Spaces-Association/metadata-broker-open-core#37]
The DRM Demo Broker loses all DSC connectors during the night. At the same time the resources of the connectors are still there. The connectors can be registered at the next day again but will be removed the next morning.

**Comment by sebplorenz** [comment]
This might be a duplicate of https://github.com/International-Data-Spaces-Association/metadata-broker-open-core/issues/32
I will check after updating to the latest broker components.

**Comment by NehaThawani44** [comment]
The test version 4.1.1-SNAPSHOT for the backend and frontend of the broker no longer shows this issue. Hence closing it.

**Comment by NehaThawani44** [comment]
The test version 4.1.1-SNAPSHOT for the backend and frontend of the broker no longer shows this issue. Hence closing it.
