### ISSUE TITLE
MobiDS specific meta data is not displayed in the DRM Test Broker.

### ISSUE THREAD

**Issue by sebplorenz** [International-Data-Spaces-Association/metadata-broker-open-core#40]
The MobiDS specific meta data is not presented in the resource detail view in the DRM Test Broker.

Broker backend and Frontend Release 4.1.1-SNAPSHOT

**Comment by NehaThawani44** [comment]
As discussed in the mobids specific tags have been added back to the UI and are visible now in Broker version 4.2.4-SNAPSHOT, hence closing it.


<img width="722" alt="mobids" src="https://user-images.githubusercontent.com/8424093/132206012-592e08ed-9557-4d6e-811d-dce3e1ff4e4c.PNG">
