### ISSUE TITLE
Strange IDs and URLs in Resource Description at the Broker

### ISSUE THREAD

**Issue by sebplorenz** [International-Data-Spaces-Association/metadata-broker-open-core#41]
In the broker frontend if you browse into the resource of a connector and click "Show JSONLD" then the jsonld of the resource is shown. But all IDs and URLs are changed and point to the broker. Especially the accessURL that should be used to access the resource is not pointing to the provider connector but to the broker.
As a consumer trying to get access to the resource I expect the connector accessURL here.

**Comment by NehaThawani44** [comment]
The accessUrl should not be rewritten while other ids should be rewritten as per the expected behavior, hence as discussed I am closing this issue as of now.
