### ISSUE TITLE
Show accessURL for connectors in connector detail view

### ISSUE THREAD

**Issue by sebplorenz** [International-Data-Spaces-Association/metadata-broker-open-core#42]
The accessURL for the connector is not shown in the connector detail view at the broker. But this information is crucial to know for the consumer user to actually access the connectors and/or resources she found at the broker.

**Comment by NehaThawani44** [comment]
AccessURL tag has been added back to the UI under connector detail view ,hence closing it.

![image](https://user-images.githubusercontent.com/8424093/132206863-8f9fb2ca-2407-4d12-8163-d5486cdf86d1.png)
