### ISSUE TITLE
Issue deployment of Azure resources

### ISSUE THREAD

**Issue by bscholtes1A** [International-Data-Spaces-Association/metadata-broker-open-core#47]
Hello,

I am trying to follow the procedure described in `scripts/README.md` in order to provision the Azure resources. 

I logged in to my Azure account using CLI and tryied `terraform init`, which failed because resource group `dagx-infrastructure` was missing. 

I created it manually and I got another error saying that storage account `dagxtstate` was missing. 

Again I created it manually and now I am getting this error:
`Error: Failed to get existing workspaces: containers.Client#ListBlobs: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ContainerNotFound" Message="The specified container does not exist.\nRequestId:7a8a8c1f-b01e-0025-3341-89fc75000000\nTime:2021-08-04T15:03:40.1040244Z"`

Am I missing something in the procedure? Are we suppose to build these resources manually? If yes could you please advise on how to do it?

Thanks in advance for your help.

Benjamin.

**Comment by sebbader** [comment]
Hello @bscholtes1A ,

can you please give me a bit more context? Why and how are you using the IDS Metadata Broker with Azure?

Best,
Sebastian

**Comment by NehaThawani44** [comment]
@bscholtes1A  Could you please provide us with some information on this otherwise, probably we will have to close this ticket.

**Comment by NehaThawani44** [comment]
@bscholtes1A  For now I am closing this issue, feel free to reopen it in the future. Also please provide us with more information on this issue.
