### ISSUE TITLE
Issue building 

### ISSUE THREAD

**Issue by jimmarino** [International-Data-Spaces-Association/metadata-broker-open-core#5]
Hi,

It looks like some of the dependencies are not resolving when I build master using: mvn clean install.

Specifically:

de.fraunhofer.iais.eis.ids:interaction:4.0.2-SNAPSHOT
de.fraunhofer.iais.eis.ids:protocol:4.0.2-SNAPSHOT
de.fraunhofer.iais.eis.ids:ecosystemintegration:4.0.2-SNAPSHOT
de.fraunhofer.iais.eis.ids:core:4.0.2-SNAPSHOT
de.fraunhofer.iais.eis.ids:connector-commons:4.0.2-SNAPSHOT

Do I need to configure a third-party repository for those artifacts? It would be nice to have the repository defined in the project pom.

Thanks!
Jim

**Comment by maboeckmann** [comment]
Hello Jim,

thank you very much for reporting this issue! My apologies for the late reply. We have now published a bunch of artifacts on the repository which is linked in this pom file and is accessible without a password. Can you please let us know if the issue is now solved?

Thanks!

Matthias

**Comment by jimmarino** [comment]
Hi Matthias,

Thanks, that resolved the issue, and I was able to build successfully. 

Are those dependencies available as open source, or are just the Maven artifacts available?

Jim

**Comment by maboeckmann** [comment]
Hi Jim,

as of now, they are not open-source and are just Maven artifacts.

Best,

Matthias

**Comment by jimmarino** [comment]
OK, thanks. One more question: Which license are they distributed under?

Cheers,
Jim

**Comment by maboeckmann** [comment]
It seems like we still need to add a license file to some of them. However, we are planning to put these artifacts under Apache 2.0 license.
