### ISSUE TITLE
Broker cannot verify DAT token

### ISSUE THREAD

**Issue by HuynhNgocThuong** [International-Data-Spaces-Association/metadata-broker-open-core#53]
Hello everyone,
I had some problem when I try to use Connector Registration of Postman collection to register Metadata Broker.
Describe:
Metadata Broker: Run by docker-compose in broker-localhost folder

- I try to run Connector Registration of Postman collection at url **https://127.0.0.1/infrastructure** but when Metadata Broker received the payload and verify DAT token, an error occurred while processing the token, beside that throw an exception [Couldn't retrieve remote JWK set: connect timed out]
- Postman:
![Screenshot_4](https://user-images.githubusercontent.com/22877952/134308737-d6ebe3f7-af89-407b-9e58-4785890cf312.png)
- Broker logs: 
![Screenshot_5](https://user-images.githubusercontent.com/22877952/134308779-42a7b54b-40db-4daa-a80c-92e9bc10ba02.png)

Please help me where I was wrong and give me solution if possible, hope you guys response ASAP. Thank you so much !

**Comment by NehaThawani44** [comment]
@HuynhNgocThuong 
This is because you need to fetch or refresh the token for this and try again.

**Comment by HuynhNgocThuong** [comment]
@NehaThawani44 
Thank you for your response !
I have checked again to make sure everything is work right but I see some things is weird. The token value is always refresh at time Postman send request to Metadata Broker but the token of response body always the same value. It seems it is hardcode.

- **Value of token:**
![Screenshot_6](https://user-images.githubusercontent.com/22877952/134454723-0e326965-ce93-4aac-9a5b-a281dbd3f635.png)

- **Request body of Postman:**
![Screenshot_7](https://user-images.githubusercontent.com/22877952/134454936-e095e9d5-c2f3-4003-b240-9792acf71400.png)

- **Response body from Broker:**
![Screenshot_8](https://user-images.githubusercontent.com/22877952/134454964-09ca9144-1bca-44c2-ac6c-07a4d8b51965.png)

Please help me where I was wrong and give me solution if possible, hope you guys response ASAP. Thank you so much !

**Comment by NehaThawani44** [comment]
@HuynhNgocThuong For now i am closing this issue, feel free to reopen it if you are still facing this issue,
