### ISSUE TITLE
Could not register connector to https://broker.ids.isst.fraunhofer.de/infrastructure

### ISSUE THREAD

**Issue by HuynhNgocThuong** [International-Data-Spaces-Association/metadata-broker-open-core#56]
Hello everyone,
I had some problem when I try to use Connector Registration of Postman collection to register Metadata Broker.
Describe:
Metadata Broker: I had unblock my IP address and use https://broker.ids.isst.fraunhofer.de
- When I Get Selfdescription on Postman, everything's work fine
- Postman:
![Screenshot_9](https://user-images.githubusercontent.com/22877952/135022351-69652ed4-e3d7-422e-bd22-befa5e53bfae.png)

- I try to run Connector Registration of Postman at URL https://broker.ids.isst.fraunhofer.de/infrastructure but I received a RejectionMessage indicating that "Connection refused" and the reason is "INTERNAL_RECIPIENT_ERROR"

- Postman:
![broker-01](https://user-images.githubusercontent.com/22877952/135021796-c8ecb6b8-f293-4713-86e7-48c3d7bad26e.png)

Please help me where I was wrong and give me solution if possible, hope you guys response ASAP. Thank you so much !

**Comment by NehaThawani44** [comment]
@HuynhNgocThuong  We are fixing this and hopefully you will not face the same issue in the newer version. PLease try registering the same back on Friday and let us know.

**Comment by HuynhNgocThuong** [comment]
Hi @NehaThawani44,
At present, I try again and receive error "502 Bad Gateway". Did you fix it yet?

Hope you guys response ASAP. Thank you so much !

**Comment by HuynhNgocThuong** [comment]
Hi @NehaThawani44 , 
At present, I am able to register a connector to https://broker.ids.isst.fraunhofer.de/infrastructure.
I appreciate your support. 
Thank you so much <3
