### ISSUE TITLE
Error in registering IDS Resource

### ISSUE THREAD

**Issue by dileep-ramachandrarao** [International-Data-Spaces-Association/metadata-broker-open-core#58]
Hello,

Currently, we are using Data Space Connector v6.3.x to register a resource in Broker and we are facing few issues and we request for your support.

As a first step, we are able to register the connector in the Broker successfully.
In the next step, we need to register the resource. During this time, we get the following error (Error code: 417):
`{
  "reason": {
    "properties": null,
    "@id": "https://w3id.org/idsa/code/INTERNAL_RECIPIENT_ERROR"
  },
  "payload": "Could not extract class of child object. ID: https://catenaxdev001akssrv.germanywestcentral.cloudapp.azure.com/broker/connectors/1410626169/1430923906/-1906547980",
  "type": "de.fraunhofer.iais.eis.RejectionMessageImpl"
}`

However, when we check the contents of the Broker's DB (i.e., Apache Fuseki), the resource which we tried to register is added into Apache Fuseki. This is a strange behavior, wherein we receive an error but also the contents are getting stored in DB.

It could be very helpful if you could help in resolving this issue.

Thanks & Regards,
Dileep

**Comment by sebbader** [comment]
Hi @dileep-ramachandrarao , are you using a running instance (e.g. demo3.iais.fraunhofer.de/ or https://broker.ids.isst.fraunhofer.de/) or do you use a locally hosted one?

**Comment by dileep-ramachandrarao** [comment]
Hi Sebastian,

We tried to re-deploy the Broker with the latest commits and this time it worked without any issues (as mentioned above).
The problem seems to be resolved on our end. Feel free to close the issue.
