### ISSUE TITLE
Broker 4.2.6-SNAPSHOT does not work with DSC 6.2.0

### ISSUE THREAD

**Issue by sebplorenz** [International-Data-Spaces-Association/metadata-broker-open-core#60]
I'm getting the following response when trying to register a resource at the Broker:

```
response=({reason=https://w3id.org/idsa/code/MALFORMED_MESSAGE, payload=The message could not be parsed due to an error in the message. Note that, due to being unable to parse this message, the ID of the correlating message is incorrect. Error: Failed to find matching enum value for https://w3id.org/idsa/autogen/iANAMediaType/e17984e3-3fa7-4944-b3b7-3cbc2eaf78a0, type=class de.fraunhofer.iais.eis.RejectionMessageImpl})
```

It seems that Broker 4.2.6 does not understand resource registration messages from DSC 6.2.0.

**Comment by NehaThawani44** [comment]
@sebplorenz  Worked fine with 4.2.7 -- Snapshot images hence closing this issue.

**Comment by syats** [comment]
@NehaThawani44  where can I get a jar file for 4.2.7, as the code is not buildable without access to fraunhofer mvn repo?
alternatively, could you update the docker image?
