### ISSUE TITLE
Make certificate path configurable from outside

### ISSUE THREAD

**Issue by sebplorenz** [International-Data-Spaces-Association/metadata-broker-open-core#61]
As an operator I want to add my certificate as a volume into to the broker container to easily update the certificate/to use different certificates for different data spaces or with different DAPS insances.

**Comment by bastianleirpo** [comment]
+1
I would highly appreciate such a feature!
Also it would be greate to make all used URLs (e.g. DAPS) configurable

**Comment by Neo28504** [comment]
+1 
As a participant of the MDS, we would also highly like that feature. Operations would be easier...

**Comment by NehaThawani44** [comment]
This feature has already been created and has been working on our instances, hence we will provide an updated image this week.

**Comment by NehaThawani44** [comment]
@sebplorenz  We have provided you the image already, it was there from the image version 4.2.7 itself.

**Comment by NehaThawani44** [comment]
@sebplorenz We have provided you the image version. @SebastianOpriel All the image versions from 4.2.8 and so on have the new change.

**Comment by sebplorenz** [comment]
Hi, @NehaThawani44 can you please point me to the documentation about how to setup the certificate path for version >= 4.2.8.

**Comment by NehaThawani44** [comment]
@sebplorenz You already know its configured already in your docker-compose opt/docker/etc/cert path is where all the certificate files are available.

**Comment by sebplorenz** [comment]
This directory is empty in my configuration.

**Comment by NehaThawani44** [comment]
Then as mentioned you need to put all the certificates there.
