### ISSUE TITLE
Unable to connect to broker infrastructure from data connector

### ISSUE THREAD

**Issue by arnabghosh3654** [International-Data-Spaces-Association/metadata-broker-open-core#62]
I am trying to set up a demo of a data connector with a broker. I am running my Data Connector on localhost:8080.  The broker is on localhost:8082. When I try to post a IDS message(eg. Resource Update Message) using swagger UI of the connector to http://localhost:8082/infrastructure , it does not accept the message. If I post the message to http://localhost:8082 instead, it does go through, but it seems it does nothing (kind of expected, as the POST api is supposed to be at /infrastructure). I am also not able to view the API at the broker end. I'd appreciate any help on this issue.

**Comment by NehaThawani44** [comment]
@arnabghosh3654  Can you please try to pull the latest code and check if the communication is working, if not it would be great if you could provide the error message that you are getting.
