### ISSUE TITLE
Feature: Admins can delete connectors and resources

### ISSUE THREAD

**Issue by sebplorenz** [International-Data-Spaces-Association/metadata-broker-open-core#63]
As a Broker administrator I need a simple way to delete a resource or a connector, because there are connectors and resources that cannot be unregistered by the connector admins themselves.

E.g. IDs of resources are created by the connector automatically. This is intended. If the database of a connector is deleted for whatever reason then a resource with the same ID cannot be recreated. Since only resources that exist on a connector can be deleted by a connector there is no way to delete a previously existing resource.

**Comment by NehaThawani44** [comment]
@sebplorenz  As discussed earlier the resources were not being removed from indexing but in the newer versions, they are deleted from Indexes also just like Connector.

**Comment by NehaThawani44** [comment]
@sebplorenz  This issue has been fixed and we have provided you with the newer version. Hence I am closing this ticket.

**Comment by sebplorenz** [comment]
Do we have a delete button for connectors and/or resources in the Broker now?

**Comment by sebplorenz** [comment]
Again, do we have a delete button now. I have a request for deleting a connector from a customer. Since the customer has updated his connector to a new version (probably with another name), he is not able to delete the old entry in the broker. Thus having two entries of the connector in the broker.
