### ISSUE TITLE
Outdated Broker Certificate

### ISSUE THREAD

**Issue by SebastianOpriel** [International-Data-Spaces-Association/metadata-broker-open-core#64]
The keystore ( broker-core/src/main/resources/isstbroker-keystore.jks) contains an outdated broker certificate:
```
Certificate Information:
Common Name: 49fa9815-9555-4038-8a9a-4e36de37bf45
Subject Alternative Names: broker.ids.isst.fraunhofer.de
Organization: Fraunhofer
Organization Unit: ISST
Country: DE
Valid From: November 28, 2018
Valid To: November 27, 2020
Issuer: IDS Test SubCA 2018, Fraunhofer
Serial Number: 34 (0x22)
```

**Comment by NehaThawani44** [comment]
@bastianleirpo  The certificate has been updated on all our instances. Could you please provide me with the instance of broker you are using?

**Comment by bastianleirpo** [comment]
As I remember I downloaded the repo and tried to run it locally. it was the main repository with the aboves mentioned path to the keystore. If that is not the case I need to check my EDI

**Comment by NehaThawani44** [comment]
@bastianleirpo once there is an updated version to the open-source broker, I would request you to pull the code and rerun it. Also which server instance are you using as of now? just to make sure if the new jks are already available on the instance you are using.

**Comment by NehaThawani44** [comment]
@SebastianOpriel The jks available at the following path expires in February 2023.  Hence I will be closing this issue. Please find the image for reference.
![image](https://user-images.githubusercontent.com/8424093/143947773-340f71ac-9812-47e2-b372-724e199d66c6.png)

![image](https://user-images.githubusercontent.com/8424093/143947480-c323f405-b754-4dd8-8df6-bce13e4f3add.png)

**Comment by SebastianOpriel** [comment]
Dear @NehaThawani44 I checked the jks again as it was updated by @sebbader 15 days ago, who put the new certificate into the jks (see https://github.com/International-Data-Spaces-Association/metadata-broker-open-core/commits/master/broker-core/src/main/resources/isstbroker-keystore.jks). So no outdated certificates anymore. Thanks!
