### ISSUE TITLE
DAPS port not processed correctly

### ISSUE THREAD

**Issue by SebastianOpriel** [International-Data-Spaces-Association/metadata-broker-open-core#65]
When a DAPS is used, that is available under a specific port (e.g. jwks.trustedHosts=localhost:4567 <- see properties file), an exception is thrown at 
`de\fraunhofer\iais\eis\ids\ecosystemintegration\4.1.3-SNAPSHOT\ecosystemintegration-4.1.3-20210811.160850-5.jar!\de\fraunhofer\iais\eis\ids\component\ecosystemintegration\daps\DapsSecurityTokenVerifier.class` like 110 with the cause 
`de.fraunhofer.iais.eis.ids.component.ecosystemintegration.daps.JWKSException: JWT issuer '[localhost:4567]' not found in the list of trusted issuers.`

If one adds also `localhost` to the jwks.trustedHosts (jwks.trustedHosts=localhost:4567,localhost) the exception is not thrown.

But: In `de\fraunhofer\iais\eis\ids\ecosystemintegration\4.1.3-SNAPSHOT\ecosystemintegration-4.1.3-20210811.160850-5.jar!\de\fraunhofer\iais\eis\ids\component\ecosystemintegration\daps\JWKSFromIssuer.class` line 44 the URI's host of issuer "http://localost:4567" is called with specific path, which is in the end http://localhost/.well-known/jwks.json. The problem is that the port is missing, and therefore the json can't be fetched.

**Comment by sebbader** [comment]
Hi @bastianleirpo, that's indeed a very interesting case. I'll put in on our internal bug list and let you know when we have a fix.

**Comment by sebbader** [comment]
I just created a bugfix for the ecosystemintegration section that you have pointed out. Review is pending, and then it will be shipped with either ecosystemintegration:4.2.8-SNAPSHOT or ecosystemintegration:4.2.9-SNAPSHOT (proper release of course if you could wait a bit :-))

**Comment by NehaThawani44** [comment]
@sebbader The newer versions with 5.0.0  and so it will have this change, hence I am closing it now.
