### ISSUE TITLE
Potential mistake in Docker-compose file 

### ISSUE THREAD

**Issue by bastianleirpo** [International-Data-Spaces-Association/metadata-broker-open-core#68]
Hi,

it seems strange, that the component_cataloguri refers to /connectors endpoint. Can you verify that this is correct? Might it be catalog/ endpoint?

https://github.com/International-Data-Spaces-Association/metadata-broker-open-core/blob/e236427c4044e22f70459bac710c0eb1477ea8b6/docker/composefiles/broker-localhost/docker-compose.yml#L24

**Comment by sebbader** [comment]
Hello @bastianleirpo,

That's used internally to match the identifiers given by the Metadata Broker to the coming REST API. That case requries a so called BaseURI that contains the domain plus the path to the catalog endpoint.
Example in a productive environment:
- COMPONENT_CATALOGURI=https://<my server domain name>/<path to the catalog endpoint from outside>/

That's nothing that can be set for all Metadata Broker instances globally, so I don't see it as a bug but rather as a input parameter at start time.

**Comment by NehaThawani44** [comment]
@sebbader @bastianleirpo As discussed this is not a potential mistake but a required configuration I am closing this ticket.
