### ISSUE TITLE
Endpoint selectQuery missing

### ISSUE THREAD

**Issue by SebastianOpriel** [International-Data-Spaces-Association/metadata-broker-open-core#82]
In Broker Open Frontend SparQL request are proxied through mongoDB handler towards the brokers Endpoint /selectQuery, which is not available in this package. I found a Java class locally, which might do the job and might be missing in this repository: index-common/.../FrontendEnpoints.java

**Comment by NehaThawani44** [comment]
Hello @SebastianOpriel I this means that the routing from open-frontend to meta-data-broker-core backend is not right
?
I will check the flow and write you here.

**Comment by SebastianOpriel** [comment]
You might have a look into the broker. There is no API endpoint for handling selectQuery requests from the front end. Please use the open metadata broker for testing.

**Comment by NehaThawani44** [comment]
I have added the endpoint and merged the code, please have a look at it. Closing this for now.
