### ISSUE TITLE
Docker-compose files refer to outdated IAIS repository

### ISSUE THREAD

**Issue by SebastianOpriel** [International-Data-Spaces-Association/metadata-broker-open-core#87]
As @sebbader mentioned here https://github.com/International-Data-Spaces-Association/ids-metadata-broker-open-frontend/issues/6 port 4567 seems to be outdated, but is still used in composefiles

**Comment by NehaThawani44** [comment]
@SebastianOpriel I have changed it directly as of now, hence closing this issue.
